### PR TITLE
Disable tsx syntax on typescript disable

### LINKED ISSUE #414: TSX still syntax highlighted when disabling typescript
**Describe the bug:**

I use [yats](https://github.com/HerringtonDarkholme/yats.vim) for syntax highlighting typescript and polyglot for all other languages. Until recently, setting `let g:polyglot_disabled = ['typescript']` was enough to disable polyglot's detection of typescript.

TSX files have started seeing syntax highlighting issues. Upon investigation, [this file](https://github.com/sheerun/vim-polyglot/blob/master/after/syntax/typescript.vim) appears to get loaded for typescript and requires the disable flags to be updated to `let g:polyglot_disabled = ['typescript', 'jsx']`.

I don't know enough to understand whether that's intentional or is a copy/paste issue from its javascript counterpart. The comment block at the top refers to `javascript.jsx` so I suspect it's the latter.

**To Reproduce:**

Set `let g:polyglot_disabled = ['typescript']` and load a TSX file. JSX and styled-components regions are still highlighted.

### PR DESCRIPTION
**Pull request by sheldonkwok**
Fixes #414

### CODE REVIEW

**Comment by rosshadden** [comment]
Thank you! This fixes the syntax problems I have had for months but haven't sucked it up and investigated until today.

**Comment by sQVe** [comment]
@sheerun Would it be possible to get this merged? This issue is really killing my vibe.

**Comment by sQVe** [comment]
Related: https://github.com/sheerun/vim-polyglot/issues/428

**Comment by sheerun** [comment]
I cannot merge this as we don't modify files that were imported by `build` script. So either this script needs to be fixed or we need to change / disable this plugin.

**Pull request closed without merging**
