### PR TITLE
Add support for Idris2, closes #534

### LINKED ISSUE #534: [Add language] Add support for Idris 2 as Idris 1 is slowly reaching EOL
The current release of vim-polyglot contains support for Idris 1. With Idris 2 being released on 1 April this year, Idris 1 will slowly be reaching its EOL.

There is a new vim plugin for Idris 2, hosted here: https://github.com/edwinb/idris2-vim

Since Idris 2 is meant as a successor to Idris 1, there is no difference in the file extensions, leading to the wrong plugin being loaded when working on Idris 2 files. Unfortunately, Idris 2 [is not backwards compatible](https://idris2.readthedocs.io/en/latest/updates/updates.html) with Idris 1 and we're currently in the awkward phase where both Idris 1 and Idris 2 are used since Idris 2 is not fully ready to succeed Idris 1 yet. I don't know if it is possible, but something like a prompt to ask which plugin to load when opening `.idr`-files would be very neat.

### PR DESCRIPTION
**Pull request by CodingCellist**
Since the file extensions are the same for Idris 1 and 2, the heuristics check for a version declaration at the top, e.g. `-- Idris 1` or
`-- Idris2`. This is not case sensitive, and there does not have to be a space before the number. If this hasn't been specified, there are a couple of keywords to do with the `%access` and `%language` pragmas, as well as the way packages work, which we can check to see if we're using Idris 1, since [they were removed](https://idris2.readthedocs.io/en/latest/updates/updates.html) in Idris 2. Finally, it is possible to overwrite the heuristics entirely by setting the variable `g:filetype_idr`.

### CODE REVIEW

**Comment by sheerun** [comment]
Is this official way of marking idris / idris2 files? (I mean comment)

**Comment by CodingCellist** [comment]
> Is this official way of marking idris / idris2 files? (I mean comment)

Unfortunately not. There does not exist an official way of indicating which version, but the files are identical in terms of content and extensions, apart from the keywords and pragmas mentioned above. That's why I suggested a prompt or something in the issue.

If the PR cannot be accepted because it's not the official way, that's fair enough. But I don't quite know how the distinction would be made in this case...

**Comment by sheerun** [comment]
I think it can stay for now.

Thank you I've reviewed it and pushed some fixes and tests, it looks good :)

I think it needs some more changes:
- it seems %language is not deprecated entirely but only some of its pragmas
- %access pragma has been removed entirely so I guess we don't need \(private\|export\|public export\|public\) ?
- could you add filetypes and tests for lidris2? (literate idris, maybe also heuristics for it, if it applies)
- could you add more tests? at least one for each heuristic
- idris-response also needs to be added to idris2

**Comment by CodingCellist** [comment]
Awesome! I'm aware it's not perfect, but it was the least intrusive way I could think of easily distinguishing the two. Thanks for checking things :)

Concerning the pragmas:
- None of the `%language` pragmas are supported in Idris 2 at the moment, but may be added later ([docs](https://idris2.readthedocs.io/en/latest/updates/updates.html#language-pragmas)). So for now the heuristic should hold, no?
- `%access` is still available in Idris 1, so the heuristic sets the file type to Idris 1 if `%access` is being used (we know we're not writing Idris 2, because we wouldn't be able to use `%access` in that). But you're right that we probably don't need `(private|export|public export|public)`.

I'll have a look at the file types, tests, etc. Might not get around to it before tomorrow though.

**Comment by sheerun** [comment]
I think they only tell about *experimental* extensions of *idris 1* . Idris 2 has its own experimental extensions e.g. like https://idris2.readthedocs.io/en/latest/reference/postfixprojs.html

**Comment by CodingCellist** [comment]
> I think they only tell about _experimental_ extensions of _idris 1_ . Idris 2 has its own experimental extensions e.g. like https://idris2.readthedocs.io/en/latest/reference/postfixprojs.html

Ah sorry, I misunderstood the docs. I'll adjust the heuristic to reflect the stuff supported in Idris 1 and Idris 2.

**Comment by CodingCellist** [comment]
There is one commented-out `.ipkg` test because the linguist used for Idris 1 does not detect `.ipkg` files as Idris files, despite the vim plugin working with them as expected.

Concerning literate idris, the tests fail when using the test framework, but the examples work when using files:

A `something.lidr` file containing
```
Some test plaintext

> --idris1
> myfact : Nat -> Nat
> myfact Z = 1
> myfact (S k) = (S k) * myfact k

More plaintext
```
correctly returns the filetype `idris` and loads the idris 1 plugin.

And a `something.lidr` file containing
```
Some test plaintext

> --idris2
> myfact : Nat -> Nat
> myfact Z = 1
> myfact (S k) = (S k) * myfact k

More plaintext
```
correctly returns the filetype `idris2` and loads the idris 2 plugin.

**Comment by sheerun** [comment]
I think it's because you're using in tests single quotes instead of double quotes (with single quotes \n is literal).

**Comment by CodingCellist** [comment]
> I think it's because you're using in tests single quotes instead of double quotes (with single quotes \n is literal).

So it was. Should be fixed now.

**Comment by sheerun** [comment]
thank you, I've pushed final fixes

**Pull request merged**
