### PR TITLE
[Docker] Only spell check syntax marked with @Spell

### PR DESCRIPTION
**Pull request by MichaelAquilina**
Before:

After:

Related PR: https://github.com/ekalinin/Dockerfile.vim/pull/64

### CODE REVIEW

**Comment by MichaelAquilina** [comment]
@sheerun polite about this PR :)

**Comment by sheerun** [comment]
Please contribute this to upstream repositories, we don't modify imported files

**Comment by MichaelAquilina** [comment]
@sheerun already did so but the project seems potentially unmaintained - in which case what do you do then?

**Comment by sheerun** [comment]
If it won't be merged in say a month you can make a fork and I'll use it instead

**Pull request closed without merging**
