### PR TITLE
Check if TestFiletypeFuncs exists before defining it

### LINKED ISSUE #783: Calling filetype twice gives an error of already defined function TestFiletypeFuncs
**Does this bug happen when you install plugin without vim-polyglot?**

No

**Describe the bug:**

If you are calling `filetype` twice in your `.vimrc like

```vim
filetype off

filetype plugin indent on
```

you'll receive an error of

```
Error detected while processing C:\Users\userxxxx\_vimrc[659]..C:\Progr
am Files (x86)\Vim\vim82\filetype.vim:

line 2530:

E122: Function TestFiletypeFuncs already exists, add ! to replace it
```

This happens because you've a copy of the original filetype.vim which is sourced:

```
   function TestFiletypeFuncs()
	Last set from ~\vimfiles\bundle\vim-polyglot\extras\filetype.vim line 2509
1    let output = ''↲
2    for f in a:testlist↲
3      try↲
4        exe f↲
5      catch↲
6        let output = output . "\n" . f . ": " . v:exception↲
7      endtry↲
8    endfor↲
9    return output↲
   endfunction
```

This is a comment from Bram on this:

> Looks like a copy. That plugin should check if the function already exists, and skip it if it does exist.
> Or use a different name.
>
> I guess previously "function!" was used. But the "!" is now not needed when loading a script file a second time. And it covers up  mistakes like you just noticed, that a function defined elsewhere is overwritten.

**To Reproduce:**

- VIM Patch 8.2.4500
- Something like this in your `.vimrc`

```vim
filetype off

filetype plugin indent on
```

### PR DESCRIPTION
**Pull request by oalders**
Fixes #783

This appears to fix the issue for me. Not sure if this is the best way to do it. Happy to rework the PR.

https://github.com/vim/vim/issues/9890 is also helpful for context.

### CODE REVIEW

**Comment by Frederick888** [comment]
It seems Neovim 0.7.0 has got the change as well, and I can confirm this PR also fixes it on Neovim.

**Comment by sheerun** [comment]
Thank you

**Comment by hiberabyss** [comment]
> Thank you

Seems the code is not merged.

image

**Comment by hiberabyss** [comment]
> Thank you

@sheerun The code is not merged.

image

**Comment by sheerun** [comment]
@hiberabyss I forgot this file is automatically fetched from upstream vim repository. It needs to be fixed there, not here. I've created issue to track this: https://github.com/sheerun/vim-polyglot/issues/793

**Comment by ptzz** [comment]
> @hiberabyss I forgot this file is automatically fetched from upstream vim repository. It needs to be fixed there, not here. I've created issue to track this: #793

Could you explain the background for the automatic fetching (the "Update" commits I assume)? Doesn't those files already exist in the shipped vim runtime? Or you need to make sure they match the plugin version or something..?

**Comment by sheerun** [comment]
Build script (https://github.com/sheerun/vim-polyglot/blob/master/scripts/build) is using packages defined in https://github.com/sheerun/vim-polyglot/blob/master/packages.yaml to fetch all of them and merge into what becomes vim-polyglot. All fixes not related to merging process go to individual packages, not here

**Comment by hiberabyss** [comment]
Maybe we could have filetype.vim locally, avoid generated by build script.

**Comment by ptzz** [comment]
Thanks @sheerun. I took a stab at fixing it in #796 by patching `filetype.vim` after fetching upstream.

**Pull request merged**
