### PR TITLE
Add support for Racket

### PR DESCRIPTION
**Pull request by jcmdln**
I've been using this plugin for a little while now and really enjoy it, though when I began to use [Racket](racket-lang.org) in Vim rather than Emacs or DrRacket the syntax highlighting was fairly annoying. I've come across [wlangstroth/vim-racket](project: https://github.com/wlangstroth/vim-racket) thanks to it being mentioned in the Racket documentation, and thanks to the excellent work done already performed by the contributors it was a breeze to include it to polyglot.

This was tested with vim-plug and from my testing is working wonderfully thus far, though any comments/criticisms are greatly appreciated!

### CODE REVIEW

**Comment by jcmdln** [comment]
Hmm, this seems to not be loaded properly in some scenarios. Closing for now while I work on this.

**Comment by munyari** [comment]
@jcmdln can you expand on what you meant with the above comment? Did you make any progress?

**Comment by jcmdln** [comment]
I apologize for the incomplete thought @munyari though I'm happy to clarify! When I attempted to add support for this initially, I was able to load `.rkt` files though when opening such files I had to source my vimrc, though to be honest I've been using another editor as my daily driver. I'll take a look and see if I can resolve the issue and report back when I'm able to confirm it works correctly. Thanks for checking on this!

**Comment by munyari** [comment]
Thanks for coming back to it @jcmdln! In my experience, vim-racket seems to work fine as a standalone plugin. Did you only have to manually source your vimrc when you used it as a part of polyglot?

**Comment by jcmdln** [comment]
That is exactly correct @munyari.

**Comment by jcmdln** [comment]
I've merged the appropriate contents of vim-racket into https://github.com/jcmdln/vim-polyglot and confirmed that it is working using the examples from https://learnxinyminutes.com/docs/racket/ and this time I did not experience my prior issues. I believe it would be possible to simply copy over the appropriate files based on my testing as multi-line comments and other such features of racket are working correctly as shown in the following:

Before:


After:


I will take a look at the results of this rather dirty attempt at adding racket support and ensure that it follows the design methodology of vim-racket before I submit a pull request.

**Pull request closed without merging**
