### PR TITLE
Add sass/scss

### PR DESCRIPTION
**Pull request by KabbAmine**
The tpope's vim-haml plugin includes sass/scss runtime files, so I've just added the information in the README (And sort the languages pack list).

### CODE REVIEW

**Comment by sheerun** [comment]
Hey. Please note that this part of README is auto-generated from `build` script, so you'd need to fix it as well :)

**Comment by KabbAmine** [comment]
Done & force-pushed.

**Comment by sheerun** [comment]
I've merged sorting of packages, but I needed to remove sass/scss entry, because it duplicates vim-haml plugin.

**Comment by KabbAmine** [comment]
Good, but how to know that vim-polyglot supports sass/scss? Using the same plugin, even if the languages are not related, why not use something like `haml/sass/scss`?

**Pull request merged**
