### PR TITLE
Don't change foldlevelstart in TypeScript

### PR DESCRIPTION
**Pull request by icholy**
This has been driving me nuts.

### CODE REVIEW

**Comment by icholy** [comment]
Ping

**Comment by icholy** [comment]
@sheerun  ping

**Comment by sheerun** [comment]
@icholy This should be fixed in typescript repo. vim-polyglot only aggregates plugins.

**Comment by icholy** [comment]
@sheerun I didn't find an vim plugins in the TypeScript repo so I assumed you're pulling from https://github.com/leafgarland/typescript-vim 

If so, can you updated to the latest version?

**Comment by sheerun** [comment]
I've released 1.3.13 with updates

**Pull request closed without merging**
