### PR TITLE
Add julia files

### PR DESCRIPTION
**Pull request by spacewander**
I don't if I should remove the `autoload` part, since the majority of it(`julia_latex_symbols.vim`) is generated by script.
However, lack of this part will break down the LaTexToUnicode feature.

### CODE REVIEW

**Comment by ajpaulson** [comment]
:+1: 
Hope this can be in the next release

**Comment by sheerun** [comment]
Could you find a plugin that provides only syntax for Julia? vim-polyglot doesn't want extra complexity

**Comment by ajpaulson** [comment]
I've found http://github.com/dcjones/julia-minimalist-vim

Which is the closest thing on github to "Just syntax" for Julia. The author mentions that it is less complete than the JuliaLang official sources.

If it's not suitable then let me know and I'll get to work separating out the official syntax into a simple repo and mixing in anything useful from @dcjones repo

**Comment by sheerun** [comment]
I've release 1.14.0 with julia-minimalist-vim syntax, but sincerely it doesn't look extremely nice :) 

If you want you want, you can suggest/create another repository.

**Comment by dcjones** [comment]
I threw those syntax files together for my own personal use because I thought the official ones, at least last time I used them, were overly complex and slow.

I should warn you, it's not kept as up to date as the official ones. For example, julia added multiline comments a while ago, but I never got around to adding support because I don't really care for multiline comments. There are also some idiosyncratic features you may want to remove: specifically support of ragel syntax.

**Comment by sheerun** [comment]
Yes, I'm somewhat concerned about ragel, but I decided to add it anyway..

I'll reiterate this integration when I find free time.

**Comment by ajpaulson** [comment]
I've begun a stripped down fork of the official JuliaLang vim plugin to *just* syntax: https://github.com/ajpaulson/julia-syntax.vim

If that looks good it could possibly be a better alternative

**Pull request closed without merging**
