### PR TITLE
Fix function already exists error

### LINKED ISSUE #441: Error after update : Function RacketDetectHashLang already exists
**Does this bug happen when you install plugin without vim-polyglot?** No.

**Describe the bug:** After updating vim-polyglot throught vim-plug (:PlugUpdate) in Neovim, I got the following error : 

> Error detected while processing /home/foobar/.local/share/nvim/plugged/vim-polyglot/ftdetect/polyglot.vim : 
> line 1123
> E122: Function RacketDetectHashLang already exists, add ! to replace it.

**To Reproduce:** Update to last version of vim-polyglot(?)

### PR DESCRIPTION
**Pull request by facto**
Fixes #441

### CODE REVIEW

**Comment by sheerun** [comment]
please contribute this to upstream

**Comment by facto** [comment]
Why was this approved then closed? I see nothing about 'upstream' in the README.

**Comment by sheerun** [comment]
Upstream repositories are repositories of plugins vim-polyglot bundles into one. In this case it's https://github.com/wlangstroth/vim-racket which is listed in the readme

**Comment by sheerun** [comment]
@rxmarbles Is not a contributor of this repository so his approval doesn't mean anything

**Pull request closed without merging**
