### PR TITLE
Restore vim-svelte

### PR DESCRIPTION
**Pull request by john-kurkowski**
These files were lost in 56121b4e27cb48efb17be55a969b2f0d725266f8. The upstream no longer uses the branch name `master`.

### CODE REVIEW

**Comment by john-kurkowski** [comment]
Build failure tracked in #519.

**Comment by sheerun** [comment]
`build` script needs to be updated instead. how to tell what is the main branch to clone?

**Comment by sheerun** [comment]
thanks @sveltejs for additional work, by the way

**Comment by sheerun** [comment]
sorry, thanks goes to @evanleck

**Pull request closed without merging**
