### PR TITLE
Add LLVM support

### PR DESCRIPTION
**Pull request by wdv4758h**

### CODE REVIEW

**Comment by sheerun** [comment]
Thank you

**Comment by sheerun** [comment]
Sorry I need to revert this as llvm repository takes too long to download for build. Feel free to extract vim plugin to separate repository and I'll include it instead

**Comment by wdv4758h** [comment]
How long are we talking about ? I run the build on my laptop here, the whole build processing took about 30 seconds. Probably it's the internet speed ?

Since I'm not the maintainer of llvm repo and I don't want to maintain another llvm vim support repo. I will run the build on my local with this then.

I've been using my fork of vim-polyglot for a while, I'm fine with it. :smile:

**Comment by sheerun** [comment]
I'll recheck but while build slowed down 2x when I merged this

**Comment by myfreeweb** [comment]
You don't need the LLVM repo itself, there's a very nice vim repo I've been using: https://github.com/rhysd/vim-llvm

**Comment by sheerun** [comment]
Sounds better, I've added it to vim-polyglot, thanks!

**Pull request merged**
